backend:
  name: github
  repo: thomasfaller/gatsbyjs-netlifycms-blog

media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Post
    folder: blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
